image: python:latest

pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  before_script:
    - pip install mkdocs==1.6.1
  script:
    - mkdocs build --strict --verbose -f mkdocs.yml
  artifacts:
    paths:
      - public
