name: Build and Deploy BlueOS Extension

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy BlueOS Extension
        uses: BlueOS-community/Deploy-BlueOS-Extension@v1.2.0
        with:
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: ${{ vars.IMAGE_NAME }}
          my_email: ${{ vars.MY_EMAIL }}
          my_name: ${{ vars.MY_NAME }}
          org_email: ${{ vars.ORG_EMAIL }}
          org_name: ${{ vars.ORG_NAME }}
