name: Deploy BlueOS Extension Image

on:
  # Automatically run when a new commit is added to the repository
  push:
  # Automatically run when someone makes a Pull Request to the repository
  #pull_request:
  # Run manually
  #workflow_dispatch:
  # NOTE: caches may be removed if not run weekly
  #  -> may be worth scheduling for every 6 days

jobs:
  deploy-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Debug secrets and variables
        run: |
          echo "DOCKER_USERNAME is set: ${{ secrets.DOCKER_USERNAME != '' }}"
          echo "DOCKER_PASSWORD is set: ${{ secrets.DOCKER_PASSWORD != '' }}"
          echo "MY_NAME: ${{ vars.MY_NAME }}"
          echo "MY_EMAIL: ${{ vars.MY_EMAIL }}"
          echo "ORG_NAME: ${{ vars.ORG_NAME }}"
          echo "ORG_EMAIL: ${{ vars.ORG_EMAIL }}"

      - name: Clear Docker cache
        run: |
          docker builder prune -f
          docker buildx prune -f

      - name: Deploy BlueOS Extension
        uses: BlueOS-community/Deploy-BlueOS-Extension@v1.2.0
        with:
          docker-username: ${{ secrets.DOCKER_USERNAME }}
          docker-password: ${{ secrets.DOCKER_PASSWORD }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: 'br-c3-data-review-app'          
          author: ${{ vars.MY_NAME }}
          author-email: ${{ vars.MY_EMAIL }}
          maintainer: ${{ vars.ORG_NAME }}
          maintainer-email: ${{ vars.ORG_EMAIL }}
